language: node_js
sudo: false
env:
  global:
    secure: zc6ST6piTTd4IJR0vPt1ulY785Rsk4WnVl6WuZkBzQKU2odRXvL6Ika3J5An5Q7lb1sw9je6RB4vQZjpHZhxV3aqC7UlgTfEgVQj0eDovwMJoTVE68vfjxp7RedfbqsmjIU61fxZuatGroliqWBdR69pEHxsw2JBJWO0lKXFD+xWeYKVy/wdZPE3WCfyCXI+vOSh42ECWSDKcP7S5QD2vO4oQUb/zvb8aQ1mIROjSuwK2bkveYoJjXvActhxeUCbVgx6i9ggaJp5LBeW9oXcOpYZRwLB1q9mBPNkvbf93myLfzeWdfFLUjqgafwd2bWJiT5tsy2x92Lyx3GGViHTkggDbQy0EQhMYQ5uFN9Ir9yKVLJyQ2ZKY7ZX2j7nqe9KVRxk/MiPykoFO1JfG6dhO5LAsx7v+qi8d300ZbVi8DwjMZLTtNF7ul8MW8xAp71w/sJ/6Wfe2ot+8jLpzGcusZp0bbWbi7oyzeu2+PCn5SHTLM9HD1cIWvqueIYIzvVklR9k8cnQg17X/OEsH/yXW1VuA/SbP6zQtZ7is7qKHF5nceH3Ok+5cpOqPOvoJ7cRHjKZEckEMGMX0PkfBQQoY9zk0r5Uij6MmtaPRJkIrn2Unf8i9M/1/o61pCPa/WVBIHFMh5v7juyZOzEcb5SCoYTYX8F0vRpPVp8nq4jLHaI=
node_js:
- stable
before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi
install:
- npm install
script:
- npm run vscode:prepublish
- npm run lint
- ./node_modules/.bin/vsce package
before_deploy:
- ./node_modules/.bin/vsce package
deploy:
  - provider: releases
    api_key:
      secure: lyw7X6Ooor2NiQLmVQ1jlgYQt7vRdXib/s3oZfHq6wGEtnkwyBkNU2l4ZKUGnv4y4y2BuYrB91e/sgxclsOUtnGCrMr+GDYPHDq5WOdlUbRMITZRak0SqXeCUvU8S/yqo5c57zX97G0xhhnJD5xdz7Ru8S6VV8nH0DqyBnf/R0PUtQXe3TbHbRqTvmX3Qnk9uEAaatiZ9XxlP2ZxEIFtG7KT7VU1ir+Qyr+jdhycp8MyNo1e2yiJbTdhobUDeEV/kjXymiV+KMS/NipOs5mjNlLVWaoFbNTBFz9YvSAdcS01Br9aC73ke6w+gSGh7pmIdrMQVeMKWv41JQwIbDqcE8s9gqFR7EUlHJSFIjB0CeGW8icczQXoTyQqRbqBHV8CQZxdFvauUOQXgDJfkCnZpiE5wgJcX6I4vctBAnXcKvj0uqNmann5d9ywVXZVPW6MpWHB0EKnGK4/HkwJ0cV9pWizos7UxL673klklrQV/1sr37VYNqvyuNmdVseuKC67jAWhisddydCICbguw/QVDdMQ7f7c5dHe8Q8YZM+aGezEcJOpu2ZnYbLxRKfyywLCMoSONMnLQ2tVlR3PbC0UZJROEe327q2YXn9BAMgpAajaoENDmXdVQsmDU63Iuw/tB4auoKUh+OY7chcBChTG/3aOpi2H6T8S1Tf9K07tOmw=
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    on:
      repo: derekbekoe/vscode-spot
      tags: true
  - provider: script
    script: ./node_modules/.bin/vsce publish -p $VSCE_TOKEN
    skip_cleanup: true
    on:
      repo: derekbekoe/vscode-spot
      tags: true
