language: node_js

sudo: false

node_js:
  - 'stable'

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install

script:
  - npm run vscode:prepublish
  - npm run lint
  # - npm test
